name: Lint - Telegram Group Messages Scraper

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install Dependencies
        run: |
          pip install ruff
      - name: Lint python projects
        run: |
          ruff check .